name: Ci cd pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test django app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python manage.py test 
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}